### ISSUE TITLE
Restore Automatic Deployments

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro.github.io#22]
After the announcement of [several layoffs at Travis CI](https://www.reddit.com/r/devops/comments/at3oyq/it_looks_like_ibera_is_gutting_travis_ci_just_a/), we are not using it anymore. We should figure out an alternative CI service to automate the deployments.

**Comment by astrojuanlu** [comment]
From the moment, this works locally: `make publish-to-github-force GITHUB_PAGES_REMOTE=git@github.com:poliastro/poliastro.github.io.git`

**Comment by astrojuanlu** [comment]
...we have been actually using it all this time.

https://travis-ci.org/poliastro/poliastro.github.io

**Comment by DhruvSondhi** [comment]
Hello, Does this mean that we are going with something else or are we returning back to Travis after some tweaks?

**Comment by astrojuanlu** [comment]
Let's use something else! GH Actions, Circle CI, or Azure Pipelines.

**Comment by DhruvSondhi** [comment]
According to my initial impressions, it seems so that Circle CI is cleaner then GitHub Actions. [I haven't checked the status with any of them but from the dashboard menu]
Also, GitHub actions will be integrated directly into GitHub, which is a plus point. 
GitHub Actions is easier to set up though as we need to add the config file in the `.github` folder 😄 and many people are switching to GitHub Actions 🤔 

*PS: I was thinking that we may use something else this time as Azure is being used on the Main Repository 😓*

**Comment by astrojuanlu** [comment]
Addressed in #69! We now have to restore automatic deploys

**Comment by DhruvSondhi** [comment]
Partially being fixed in #73

**Comment by astrojuanlu** [comment]
Two years later, we have it 🎉 Done it in #77 + 9fec377d. Closing!
