### ISSUE TITLE
Blog theme update

### ISSUE THREAD

**Issue by jorgepiloto** [poliastro/poliastro.github.io#44]
I think it would be interesting to update the current blog theme. This might be solve https://github.com/poliastro/poliastro/issues/712.

:bulb: **Posible ideas**

Some months ago I found a [very cool scientific theme](https://yourfreebies.github.io/sciblog/). I got rid of the Menu button but substituting it with a header menu like the one shown in my personal website, see [here](https://on-orbit.dev/). 

Previous theme implies moving from Pelican to Jekyll, please comment if this might be interesting or we should remain in Pelican. Of course, all the actual blog posts would remain untouched and adapted to the new theme.

Furthermore, different header menu sections such us: home, blog, docs, contributing and about might be added making a more powerful poliastro web page.

**Comment by astrojuanlu** [comment]
I'm not a fan of that theme, to be honest :sweat_smile: I think ours is better! The whitespace is not very well handled, and also the theme itself was last updated in 2018.

On the other hand, I don't think changing the theme solves #712, because the blog would still have the structure of a blog.

Therefore, too much change (theme, blogging engine, Ruby instead of Python) for too little gain.

Let's continue discussing about #712 there. With your permission, I am closing this issue because I think the theme of the blog is less important than other issues we have :)
