### ISSUE TITLE
Consider not using conda

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro.github.io#6]
The dependencies are not at all complex, and with conda the installation times are too long to be worth it.

**Comment by anhiga** [comment]
I've been doing some checks in my own Github Page, with the same content as poliastro blog, and I've been able to deploy with only four dependencies: `pip install pelican markdown ipython notebook`.
You can check it out in [my GHP](anhiga.github.io). I guess that other dependencies will be needed in order to use other pelican functionalities.

**Comment by astrojuanlu** [comment]
Why not starting a pull request and check if everything works? :)

**Comment by astrojuanlu** [comment]
Closed in #9!
